# Generated by Django 5.1.4 on 2025-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0002_rename_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
